services:
  agent-workshop:
    build: .
    container_name: agent-workshop
    volumes:
      - .:/app
    env_file:
      - app/.env
    ports:
      - "8000:8000"
    command: adk web --host 0.0.0.0
